// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6SWrEUxZ-w6B91577TEl_gq4SsnVrB4',
    appId: '1:1036357616131:web:94ddf934b15947ffec4436',
    messagingSenderId: '1036357616131',
    projectId: 'barang-f2c85',
    authDomain: 'barang-f2c85.firebaseapp.com',
    storageBucket: 'barang-f2c85.firebasestorage.app',
    measurementId: 'G-X1FQKE8BRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeNMHFsI7dF-vhjk0hps68ffzwYxHbzcE',
    appId: '1:1036357616131:android:be7ebdc91d72e933ec4436',
    messagingSenderId: '1036357616131',
    projectId: 'barang-f2c85',
    storageBucket: 'barang-f2c85.firebasestorage.app',
  );
}
